import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";
import { formatIdr, toNumber } from "@/lib/money";

export default async function AdminProductDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdminPage(); const { id } = await params; const product = await prisma.product.findUnique({ where: { id }, include: { category: true } }); if (!product) notFound();
  const margin = product.marginType === "FIXED" ? formatIdr(product.marginFixed) : product.marginType === "PERCENTAGE_PLUS_FIXED" ? `${toNumber(product.marginPercentage)}% + ${formatIdr(product.marginFixed)}` : `${toNumber(product.marginPercentage)}%`;
  return <div className="mx-auto max-w-4xl"><Link href="/admin/products" className="text-sm font-semibold text-indigo-600">← Kembali</Link><div className="mt-5 rounded-2xl border bg-white p-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-3xl font-bold">{product.name}</h1><p className="mt-1 text-slate-500">{product.brand || "-"} · {product.category?.name || "Other"}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{product.status}</span></div>{product.imageUrl && <img src={product.imageUrl} alt={product.name} className="mt-6 h-52 rounded-xl object-cover" />}<p className="mt-6 whitespace-pre-wrap text-slate-600">{product.description || "-"}</p><h2 className="mt-8 text-lg font-bold">Rincian Harga Internal</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Item label="Harga Beli CNY" value={toNumber(product.originalPrice) > 0 ? `¥${toNumber(product.originalPrice).toLocaleString("id-ID")}` : "Belum dihitung"} /><Item label="Kurs BI yang digunakan" value={toNumber(product.exchangeRate) > 0 ? `Rp${toNumber(product.exchangeRate).toLocaleString("id-ID", { minimumFractionDigits: 2 })}` : "Belum dihitung"} /><Item label="Tanggal kurs" value={product.exchangeRateDate?.toLocaleString("id-ID") || "-"} /><Item label="Modal Barang IDR" value={formatIdr(toNumber(product.originalPrice) * toNumber(product.exchangeRate))} /><Item label="Biaya Pengiriman" value={formatIdr(product.internationalShipping)} /><Item label="Pajak / Bea" value={formatIdr(product.tax)} /><Item label="Biaya Tambahan" value={formatIdr(product.additionalCost)} /><Item label="Total Modal" value={formatIdr(product.totalCost)} /><Item label="Jenis Margin" value={margin} /><Item label="Profit" value={formatIdr(product.profit)} /><Item label="Harga Jual" value={formatIdr(product.sellingPrice)} /><Item label="Dibuat" value={product.createdAt.toLocaleString("id-ID")} /><Item label="Terakhir diperbarui" value={product.updatedAt.toLocaleString("id-ID")} /></dl></div></div>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
