"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, PackageCheck, ShoppingBag } from "lucide-react";

const orders = [
  { id: "ORD-12345678", date: "23 Agu 2026", status: "Menunggu Verifikasi", productName: "Xiaomi Smart Band 8 Pro", total: 1850000 },
  { id: "ORD-87654321", date: "15 Agu 2026", status: "Dalam Pengiriman ke Indonesia", productName: "Li-Ning Way of Wade 10", total: 3100000 },
  { id: "ORD-13572468", date: "02 Agu 2026", status: "Selesai", productName: "Pop Mart Dimoo Retro Series", total: 220000 },
];
const statusStyle: Record<string, string> = { "Menunggu Pembayaran": "bg-amber-50 text-amber-700", "Menunggu Verifikasi": "bg-orange-50 text-orange-700", "Pembayaran Diterima": "bg-emerald-50 text-emerald-700", "Barang Sedang Dibeli": "bg-blue-50 text-blue-700", "Barang Sudah Dibeli": "bg-blue-50 text-blue-700", "Pengecekan Barang": "bg-violet-50 text-violet-700", "Dalam Pengiriman ke Indonesia": "bg-indigo-50 text-indigo-700", "Sampai di Indonesia": "bg-cyan-50 text-cyan-700", "Dikirim ke Customer": "bg-blue-50 text-blue-700", "Selesai": "bg-emerald-50 text-emerald-700", "Dibatalkan": "bg-rose-50 text-rose-700" };

export default function OrdersPage() { const [active, setActive] = useState("Semua"); const filtered = active === "Semua" ? orders : orders.filter((order) => order.status === active); const filters = ["Semua", "Menunggu Pembayaran", "Menunggu Verifikasi", "Dalam Pengiriman ke Indonesia", "Selesai"]; return <main className="mx-auto min-h-screen max-w-5xl px-4 py-10 sm:px-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-wider text-[#5B3DF5]">Pesanan saya</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#0F1B38]">Status barangmu</h1><p className="mt-2 text-slate-600">Pantau setiap proses pesanan dari pembayaran hingga pengiriman.</p></div><div className="flex items-center gap-2 rounded-xl border border-violet-100 bg-[#F1EEFF] px-3 py-2 text-sm font-semibold text-[#5B3DF5]"><PackageCheck className="h-4 w-4" />{orders.length} pesanan</div></div><div className="mt-8 flex gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1.5">{filters.map((filter) => <button key={filter} onClick={() => setActive(filter)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium ${active === filter ? "bg-white text-[#5B3DF5] shadow-sm" : "text-slate-500 hover:text-slate-700"}`}>{filter}</button>)}</div><div className="mt-6 space-y-4">{filtered.map((order) => <article key={order.id} className="rounded-2xl border border-[#E6E8F0] bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-center"><div><p className="font-bold text-[#0F1B38]">{order.id}</p><p className="mt-1 text-sm text-slate-500">{order.date}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${statusStyle[order.status]}`}>{order.status}</span></div><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#F1EEFF] text-[#5B3DF5]"><ShoppingBag className="h-6 w-6" /></span><div><h2 className="font-semibold text-[#0F1B38]">{order.productName}</h2><p className="mt-1 text-sm text-slate-500">Total <span className="font-semibold text-slate-900">Rp {order.total.toLocaleString("id-ID")}</span></p></div></div><Link href={`/orders/${order.id}`} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#E6E8F0] px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-violet-200 hover:bg-[#F1EEFF] hover:text-[#5B3DF5]">Lihat Detail <ArrowRight className="h-4 w-4" /></Link></div></article>)}</div></main>; }
