"use client";

import { useState } from "react";

export function AdminExchangeRateCard({ initialRate }: { initialRate: { sellRate: number; buyRate: number | null; sourceDate: string; fetchedAt: string; provider: string } | null }) {
  const [rate, setRate] = useState(initialRate); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function refresh() { setLoading(true); setMessage(""); const response = await fetch("/api/admin/exchange-rates/cny/refresh", { method: "POST" }); const data = await response.json().catch(() => null); setLoading(false); if (!response.ok) return setMessage(data?.error || "Gagal memperbarui kurs BI."); setRate({ sellRate: data.rate, buyRate: data.buyRate, sourceDate: new Date(data.sourceDate).toLocaleString("id-ID"), fetchedAt: new Date(data.fetchedAt).toLocaleString("id-ID"), provider: "Bank Indonesia — Kurs Transaksi BI" }); setMessage(data.unchanged ? "Kurs sudah menggunakan data BI terbaru." : "Kurs Bank Indonesia berhasil diperbarui."); }
  return <section className="mt-7 max-w-2xl rounded-2xl border bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-bold">CNY / IDR</h2><p className="mt-1 text-sm text-slate-500">Kurs Transaksi BI untuk kalkulator produk China.</p></div><button onClick={refresh} disabled={loading} className="rounded-xl bg-[#D98392] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-[#C86D7D] active:bg-[#B95F70] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#EAB5C0] focus-visible:ring-offset-2 disabled:opacity-60">{loading ? "Memperbarui..." : "Perbarui Sekarang"}</button></div>{rate ? <dl className="mt-6 grid gap-4 sm:grid-cols-2"><Item label="Kurs Jual BI" value={`Rp${rate.sellRate.toLocaleString("id-ID")}`} /><Item label="Kurs Beli BI" value={rate.buyRate === null ? "-" : `Rp${rate.buyRate.toLocaleString("id-ID")}`} /><Item label="Data BI" value={rate.sourceDate} /><Item label="Fetched at" value={rate.fetchedAt} /><Item label="Sumber" value={rate.provider} /><Item label="Status" value="Data terbaru tersedia" /></dl> : <p className="mt-6 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Belum ada data kurs tersimpan. Klik Perbarui Sekarang untuk mengambil Kurs Jual BI.</p>}{message && <p className={`mt-5 rounded-lg p-3 text-sm ${message.startsWith("Bank Indonesia sementara") || message.startsWith("Gagal") ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-700"}`}>{message}</p>}<a className="mt-5 inline-block text-sm font-semibold text-indigo-600 hover:underline" href="https://www.bi.go.id/id/fungsi-utama/moneter/informasi-kurs/transaksi-bi/Default.aspx" target="_blank" rel="noopener noreferrer">Lihat sumber Bank Indonesia</a></section>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>; }
