"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

const defaultExpiry = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 16);

export function AdminQuotationForm({ requestId, currency, quantity }: { requestId: string; currency: string; quantity: number }) {
  const router = useRouter(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/admin/requests/${requestId}/quotation`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); setSaving(false); if (!response.ok) return setError(data.error || "Gagal membuat penawaran."); router.push(`/admin/quotations/${data.quotationId}`); router.refresh(); }
  return <form onSubmit={submit} className="mt-7 rounded-2xl border border-indigo-100 bg-indigo-50/40 p-5"><h2 className="font-bold text-slate-950">Buat & Kirim Penawaran</h2><p className="mt-1 text-sm text-slate-600">Nilai di bawah disimpan sebagai snapshot saat penawaran dikirim.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["productPrice", `Harga barang per unit (${currency})`], ["exchangeRate", "Kurs yang digunakan (IDR)"], ["shipping", "Ongkir / Pengiriman (IDR)"], ["additionalCost", "Biaya tambahan (IDR)"], ["serviceFee", "Biaya Jastip (IDR)"]].map(([name, label]) => <label key={name} className="text-sm font-semibold text-slate-700">{label}<input required min="0" step="any" type="number" name={name} className="field mt-1" defaultValue="0" /></label>)}<label className="text-sm font-semibold text-slate-700">Quantity<input required min="1" type="number" name="quantity" className="field mt-1" defaultValue={quantity} /></label><label className="text-sm font-semibold text-slate-700">Berlaku sampai<input required type="datetime-local" name="expiresAt" className="field mt-1" defaultValue={defaultExpiry} /></label></div>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<button disabled={saving} className="mt-5 rounded-xl bg-[#D98392] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-[#C86D7D] active:bg-[#B95F70] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#EAB5C0] focus-visible:ring-offset-2 disabled:opacity-60">{saving ? "Mengirim..." : "Kirim Penawaran"}</button></form>;
}
