"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { CircleDollarSign, FileText, Landmark, LayoutDashboard, Menu, Package, Package2 } from "lucide-react";
import { useState } from "react";
import { AdminLogoutButton } from "@/components/AdminLogoutButton";
import { AdminNotifications } from "@/components/AdminNotifications";
import { brand } from "@/lib/brand";
const navigation = [{ name: "Dashboard", href: "/admin", icon: LayoutDashboard }, { name: "Produk", href: "/admin/products", icon: Package }, { name: "Pesanan", href: "/admin/orders", icon: Package2 }, { name: "Kurs BI", href: "/admin/exchange-rates", icon: CircleDollarSign }, { name: "Request Barang", href: "/admin/requests", icon: FileText }, { name: "Pembayaran", href: "/admin/payments", icon: Landmark }];
export function AdminShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); const [open, setOpen] = useState(false); if (pathname === "/admin/login") return <>{children}</>; const sidebar = <aside className="flex h-full w-72 flex-col bg-[#3B2925] text-[#F8E8EB]"><div className="border-b border-white/10 px-5 py-5"><Link href="/admin" className="block rounded-2xl bg-[#FFF9F5] px-3 py-2"><Image src={brand.logo} alt="Titip Clei" width={220} height={80} className="h-auto w-[190px]" priority /></Link><p className="mt-3 px-2 text-xs font-semibold uppercase tracking-[0.18em] text-[#D8B5A4]">Admin Panel</p></div><nav className="flex-1 space-y-1.5 p-4"><p className="px-3 pb-2 text-[10px] font-bold tracking-[0.18em] text-[#BFA49A]">MENU UTAMA</p>{navigation.map((item) => { const Icon = item.icon; const active = pathname === item.href; return <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${active ? "bg-[#D98591] text-white shadow-sm" : "text-[#F8E8EB] hover:bg-white/10"}`}><Icon className="h-[18px] w-[18px]" />{item.name}</Link>; })}</nav><div className="m-4 rounded-2xl bg-white/5 p-4"><p className="text-sm font-semibold text-white">Titip Clei</p><p className="mt-1 text-xs text-[#D8B5A4]">Kelola pesanan dengan hangat</p></div></aside>; return <div className="min-h-screen bg-[#FFF9F5] text-[#3B2925]"><div className="fixed inset-y-0 left-0 z-50 hidden md:block">{sidebar}</div>{open && <div className="fixed inset-0 z-[60] bg-[#3B2925]/40 md:hidden"><div className="h-full w-72">{sidebar}</div></div>}<main className="min-h-screen md:ml-72"><header className="sticky top-0 z-40 flex h-20 items-center border-b border-[#EADBD4] bg-[#FFFDFC]/95 px-5 backdrop-blur md:px-8"><button onClick={() => setOpen(true)} className="rounded-xl p-2 text-[#5E4039] hover:bg-[#F8E8EB] md:hidden" aria-label="Buka menu"><Menu /></button><p className="ml-3 hidden text-sm text-[#90756E] md:block">Kelola Titip Clei dengan mudah dan rapi.</p><div className="ml-auto flex items-center gap-3"><AdminNotifications /><AdminLogoutButton /></div></header><div className="min-h-[calc(100vh-5rem)] p-5 pb-24 md:p-8">{children}</div></main></div>; }
