"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export function OrderAddressForm({ orderId, name, phone, address }: { orderId: string; name: string | null; phone: string | null; address: { recipientName: string | null; recipientPhone: string | null; addressLine: string | null; city: string | null; province: string | null; postalCode: string | null; shippingNote: string | null } }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/orders/${orderId}/address`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json().catch(() => null); setSaving(false); if (!response.ok) return setError(data?.error || "Gagal menyimpan alamat."); router.refresh(); }
  return <form onSubmit={submit} className="rounded-2xl border border-[#E8D8D1] bg-[#FFFDFC] p-6 shadow-sm"><h2 className="font-bold text-[#4B342F]">Alamat Pengiriman</h2><p className="mt-1 text-sm text-[#8B716A]">Lengkapi alamat sebelum mengunggah bukti pembayaran.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#5E4039]">Nama Penerima<input required name="recipientName" defaultValue={address.recipientName ?? name ?? ""} className="field mt-2" /></label><label className="text-sm font-semibold text-[#5E4039]">WhatsApp Penerima<input required name="recipientPhone" defaultValue={address.recipientPhone ?? phone ?? ""} inputMode="tel" className="field mt-2" /></label><label className="text-sm font-semibold text-[#5E4039] sm:col-span-2">Alamat Lengkap<textarea required name="addressLine" defaultValue={address.addressLine ?? ""} className="field mt-2 min-h-24" placeholder="Nama jalan, nomor rumah, RT/RW, kecamatan, dll." /></label><label className="text-sm font-semibold text-[#5E4039]">Kota / Kabupaten<input required name="city" defaultValue={address.city ?? ""} className="field mt-2" /></label><label className="text-sm font-semibold text-[#5E4039]">Provinsi<input required name="province" defaultValue={address.province ?? ""} className="field mt-2" /></label><label className="text-sm font-semibold text-[#5E4039]">Kode Pos<input required name="postalCode" defaultValue={address.postalCode ?? ""} inputMode="numeric" className="field mt-2" /></label><label className="text-sm font-semibold text-[#5E4039]">Catatan <span className="font-normal text-[#8B716A]">(opsional)</span><input name="shippingNote" defaultValue={address.shippingNote ?? ""} className="field mt-2" /></label></div>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}<button disabled={saving} className="mt-5 rounded-xl bg-[#D98392] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#C86D7D] disabled:opacity-60">{saving ? "Menyimpan..." : "Simpan Alamat"}</button></form>;
}
