"use client";
import { ChangeEvent, useState } from "react";
import { CheckCircle2, Clipboard, Upload } from "lucide-react";

export function PaymentForm({ orderId, bankName, accountNumber }: { orderId: string; total: number; bankName: string; accountNumber: string; accountHolder: string }) {
  const [proof, setProof] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(accountNumber); setMessage("Nomor rekening disalin."); };
  const chooseFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) return setMessage("Ukuran bukti maksimal 10 MB."); setProof(file); setPreview(URL.createObjectURL(file)); };
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!proof) return setMessage("Silakan upload bukti transfer terlebih dahulu."); setIsSubmitting(true); const formData = new FormData(event.currentTarget); formData.set("proof", proof); const response = await fetch(`/api/payments/${orderId}/proof`, { method: "POST", body: formData }); const data = await response.json(); setIsSubmitting(false); if (response.ok && data.redirectTo) window.location.assign(data.redirectTo); else setMessage(data.error || "Gagal mengirim bukti pembayaran."); };
  return <form onSubmit={submit} className="mt-6 rounded-2xl border border-[#E6E8F0] bg-white p-6 shadow-sm"><h2 className="font-bold text-[#0F1B38]">Upload Bukti Transfer</h2><button type="button" onClick={copy} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-[#F1EEFF] px-3 py-2 text-sm font-semibold text-[#5B3DF5]"><Clipboard className="h-4 w-4" />Salin Nomor Rekening</button><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Nama Pengirim<input name="senderName" className="field mt-2" placeholder="Opsional" /></label><label className="text-sm font-semibold text-slate-700">Catatan Pembayaran<input name="notes" className="field mt-2" placeholder="Opsional" /></label></div><label className="mt-5 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#E6E8F0] bg-[#F7F8FC] p-4 text-center hover:border-violet-300"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseFile} className="sr-only" />{preview ? <img src={preview} alt="Pratinjau bukti transfer" className="max-h-52 rounded-lg object-contain" /> : <><Upload className="h-6 w-6 text-[#5B3DF5]" /><span className="mt-2 text-sm font-semibold text-slate-700">Upload Bukti Transfer</span><span className="mt-1 text-xs text-slate-500">JPG, PNG, atau WEBP • maks. 10 MB</span></>}</label><button disabled={isSubmitting} className="mt-5 inline-flex h-12 w-full items-center justify-center rounded-xl bg-[#5B3DF5] font-semibold text-white hover:bg-[#4930D8] disabled:opacity-60">{isSubmitting ? "Mengirim..." : "Kirim Bukti Pembayaran"}</button>{message && <p className="mt-4 flex gap-2 rounded-xl bg-violet-50 p-3 text-sm text-[#4930D8]"><CheckCircle2 className="h-5 w-5 shrink-0" />{message}</p>}</form>;
}
