"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function PublicQuotationActions({ token, total, enabled }: { token: string; total: number; enabled: boolean }) {
  const router = useRouter(); const [dialog, setDialog] = useState<"accept" | "reject" | null>(null); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit() { if (!dialog) return; setSaving(true); setError(""); const response = await fetch(`/api/quotation/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: dialog, reason }) }); const data = await response.json(); setSaving(false); if (!response.ok) return setError(data.error || "Gagal memproses penawaran."); if (data.orderToken) router.push(`/payment/${data.orderToken}`); else { setDialog(null); router.refresh(); } }
  return <><div className="space-y-3"><button disabled={!enabled} onClick={() => setDialog("accept")} className="h-12 w-full rounded-xl bg-indigo-600 font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">Terima Penawaran</button><button disabled={!enabled} onClick={() => setDialog("reject")} className="h-12 w-full rounded-xl border border-rose-200 font-semibold text-rose-700 hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-50">Tolak Penawaran</button></div>{dialog && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><section role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-bold text-slate-950">{dialog === "accept" ? "Terima penawaran ini?" : "Tolak penawaran?"}</h2>{dialog === "accept" ? <p className="mt-3 text-sm leading-6 text-slate-600">Total pembayaranmu adalah <strong>Rp{total.toLocaleString("id-ID")}</strong> dan harga akan dikunci setelah penawaran diterima.</p> : <label className="mt-4 block text-sm font-semibold text-slate-700">Alasan (opsional)<select value={reason} onChange={(event) => setReason(event.target.value)} className="field mt-2"><option value="">Pilih alasan</option><option>Harga belum sesuai</option><option>Barang tidak jadi dibeli</option><option>Salah barang/variant</option><option>Lainnya</option></select></label>}{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button disabled={saving} onClick={() => setDialog(null)} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600">Batal</button><button disabled={saving} onClick={submit} className={`rounded-lg px-4 py-2 text-sm font-semibold text-white ${dialog === "accept" ? "bg-indigo-600" : "bg-rose-600"}`}>{saving ? "Memproses..." : dialog === "accept" ? "Ya, Terima Penawaran" : "Ya, Tolak Penawaran"}</button></div></section></div>}</>;
}
