import { Landmark } from "lucide-react";
import { notFound } from "next/navigation";
import { PaymentForm } from "@/components/PaymentForm";
import { paymentDestination } from "@/lib/payment-settings";
import { prisma } from "@/lib/prisma";

export default async function PaymentPage({ params }: { params: Promise<{ orderId: string }> }) {
  const { orderId } = await params; const order = await prisma.order.findUnique({ where: { publicToken: orderId } }); if (!order) notFound();
  return <main className="min-h-screen bg-[#F7F8FC] py-10"><div className="mx-auto max-w-4xl px-4 sm:px-6"><p className="text-sm font-bold uppercase tracking-wider text-[#5B3DF5]">Penawaran Diterima</p><h1 className="mt-2 text-3xl font-bold text-[#0F1B38]">Selesaikan Pembayaran</h1><p className="mt-2 text-slate-600">Pesananmu sudah dibuat. Silakan selesaikan pembayaran untuk melanjutkan proses.</p><p className="mt-3 text-sm font-semibold text-slate-700">Kode Pesanan: {order.orderNumber}</p><div className="mt-7 grid gap-6 lg:grid-cols-5"><div className="space-y-6 lg:col-span-3"><section className="rounded-2xl border border-[#E6E8F0] bg-white p-6 shadow-sm"><h2 className="font-bold text-[#0F1B38]">Ringkasan Pesanan</h2><p className="mt-4 font-semibold">{order.productNameSnapshot}</p><p className="mt-1 text-sm text-slate-600">Quantity: {order.quantity} · Variant: {order.variantNameSnapshot || order.variant || "-"}</p></section><section className="rounded-2xl bg-[#0F1B38] p-6 text-white"><p className="text-sm text-slate-300">Total yang Harus Ditransfer</p><p className="mt-2 text-3xl font-extrabold">Rp {order.total.toLocaleString("id-ID")}</p><p className="mt-3 text-sm text-slate-300">Nominal ini berasal dari penawaran dan tidak dapat diubah.</p></section><section className="rounded-2xl border border-[#E6E8F0] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#F1EEFF] text-[#5B3DF5]"><Landmark className="h-5 w-5" /></span><h2 className="font-bold text-[#0F1B38]">Rekening Tujuan</h2></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-500">Bank</dt><dd className="mt-1 font-bold text-[#0F1B38]">{paymentDestination.bankName}</dd></div><div><dt className="text-slate-500">Nomor Rekening</dt><dd className="mt-1 font-bold text-[#0F1B38]">{paymentDestination.accountNumber}</dd></div><div><dt className="text-slate-500">Atas Nama</dt><dd className="mt-1 font-bold text-[#0F1B38]">{paymentDestination.accountHolder}</dd></div></dl></section></div><aside className="lg:col-span-2"><section className="rounded-2xl border border-amber-100 bg-amber-50 p-6"><h2 className="font-bold text-[#0F1B38]">Cara Pembayaran</h2><ol className="mt-4 list-decimal space-y-3 pl-4 text-sm leading-6 text-slate-600"><li>Transfer sesuai nominal yang tertera.</li><li>Pastikan rekening tujuan sudah benar.</li><li>Simpan bukti transfer.</li><li>Upload bukti pembayaran.</li><li>Tunggu pembayaran diverifikasi.</li></ol></section></aside></div><PaymentForm orderId={orderId} total={order.total} {...paymentDestination} /></div></main>;
}
