import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";
import { CopyQuotationLink } from "@/components/CopyQuotationLink";

const labels: Record<string, string> = { DRAFT: "Draft", SENT: "Terkirim", ACCEPTED: "Diterima", REJECTED: "Ditolak", EXPIRED: "Kedaluwarsa" };
const money = (value: number) => `Rp${value.toLocaleString("id-ID")}`;
export default async function AdminQuotationDetail({ params }: { params: Promise<{ id: string }> }) {
  await requireAdminPage(); const { id } = await params;
  const quotation = await prisma.quotation.findUnique({ where: { id }, include: { user: true, jastipRequest: true } }); if (!quotation) notFound();
  const link = `/quotation/${quotation.publicToken}`; const phone = quotation.user?.phone?.replace(/^0/, "62").replace(/\D/g, ""); const whatsapp = phone ? `https://wa.me/${phone}?text=${encodeURIComponent(`Penawaran harga untuk request ${quotation.jastipRequest?.requestNumber ?? ""} sudah tersedia. Silakan cek penawaran melalui link berikut: ${link}`)}` : null;
  const rows = [["Harga barang", quotation.convertedProductCost], ["Exchange rate", quotation.appliedExchangeRate], ["Shipping", quotation.internationalShipping], ["Additional cost", quotation.additionalCost], ["Total cost", quotation.totalCost], ["Margin", quotation.serviceMarginValue], ["Profit", quotation.profit], ["Final customer price", quotation.finalPrice]];
  return <div className="mx-auto max-w-3xl"><Link href={`/admin/requests/${quotation.jastipRequestId}`} className="text-sm font-semibold text-indigo-600">← Kembali ke request</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-indigo-600">{quotation.jastipRequest?.requestNumber}</p><h1 className="mt-1 text-3xl font-bold">{quotation.quotationNumber}</h1></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-700">{labels[quotation.status]}</span></div><section className="mt-6 rounded-2xl border bg-white p-6"><dl className="grid gap-5 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Customer</dt><dd className="font-semibold">{quotation.user?.name || "-"}</dd></div><div><dt className="text-sm text-slate-500">Product</dt><dd className="font-semibold">{quotation.jastipRequest?.productName || "-"}</dd><dd className="text-sm">Qty {quotation.quantity} · {quotation.jastipRequest?.variant || "-"}</dd></div>{rows.map(([label, value]) => <div key={String(label)}><dt className="text-sm text-slate-500">{label}</dt><dd className="font-semibold">{label === "Exchange rate" ? Number(value).toLocaleString("id-ID") : money(Number(value))}</dd></div>)}<div><dt className="text-sm text-slate-500">Expires at</dt><dd className="font-semibold">{quotation.expiresAt?.toLocaleString("id-ID", { dateStyle: "long", timeStyle: "short", timeZone: "Asia/Jakarta" })} WIB</dd></div></dl><div className="mt-7 flex flex-wrap gap-3"><a href={link} target="_blank" rel="noreferrer" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Buka Link Penawaran</a><CopyQuotationLink link={link} />{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="rounded-xl border border-emerald-200 px-4 py-2.5 text-sm font-semibold text-emerald-700">Buka WhatsApp Customer</a>}</div><p className="mt-3 select-all text-xs text-slate-500">{link}</p></section></div>;
}
