ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'QUOTATION_REJECTED';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "requestId" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Order_quotationId_key" ON "Order"("quotationId");
