import { Image as ImageIcon, Landmark } from "lucide-react";
import { AdminPaymentActions } from "@/components/AdminPaymentActions";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";

export default async function AdminPaymentsPage() {
  await requireAdminPage();
  const payments = await prisma.payment.findMany({ include: { order: { include: { user: true } } }, orderBy: { submittedAt: "desc" } });
  return <div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-indigo-600">Pembayaran manual</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Verifikasi pembayaran</h1><p className="mt-2 text-slate-500">Periksa bukti transfer sebelum pesanan diproses.</p></div><Landmark className="h-8 w-8 text-indigo-600" /></div><div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Order ID</th><th className="px-5 py-4">Customer</th><th className="px-5 py-4">Produk</th><th className="px-5 py-4">Jumlah</th><th className="px-5 py-4">Bukti</th><th className="px-5 py-4">Dikirim</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.length === 0 ? <tr><td colSpan={8} className="px-5 py-14 text-center text-slate-500">Belum ada bukti pembayaran yang masuk.</td></tr> : payments.map((payment) => <tr key={payment.id}><td className="px-5 py-4 font-semibold text-slate-900">{payment.order.orderNumber}</td><td className="px-5 py-4"><p>{payment.order.customerName || payment.order.user?.name || payment.order.user?.email || "-"}</p>{payment.order.customerPhone && <p className="mt-1 text-xs text-slate-500">{payment.order.customerPhone}</p>}</td><td className="px-5 py-4">{payment.order.productNameSnapshot || "Pesanan custom"}</td><td className="px-5 py-4 font-semibold">Rp {payment.amount.toLocaleString("id-ID")}</td><td className="px-5 py-4">{payment.proofStorageKey || payment.proofImageUrl ? <a href={`/api/admin/payments/${payment.id}/proof`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-indigo-600 hover:underline"><ImageIcon className="h-4 w-4" />Lihat Bukti</a> : "-"}</td><td className="px-5 py-4 text-slate-500">{payment.submittedAt?.toLocaleString("id-ID") || "-"}</td><td className="px-5 py-4"><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-700">{payment.status === "WAITING_VERIFICATION" ? "Menunggu Verifikasi" : payment.status}</span></td><td className="px-5 py-4">{payment.status === "WAITING_VERIFICATION" && <AdminPaymentActions paymentId={payment.id} />}</td></tr>)}</tbody></table></div></div></div>;
}
