CREATE TYPE "PriceRoundingType" AS ENUM ('NONE', 'ROUND_1000', 'ROUND_5000', 'ROUND_10000');

ALTER TABLE "Product"
  ALTER COLUMN "originalPrice" TYPE DECIMAL(18,2) USING "originalPrice"::DECIMAL(18,2),
  ALTER COLUMN "sellingPrice" TYPE DECIMAL(18,0) USING "sellingPrice"::DECIMAL(18,0),
  ADD COLUMN "exchangeRate" DECIMAL(18,4) NOT NULL DEFAULT 0,
  ADD COLUMN "exchangeRateSource" TEXT NOT NULL DEFAULT 'BANK_INDONESIA',
  ADD COLUMN "exchangeRateDate" TIMESTAMP(3),
  ADD COLUMN "useManualRate" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "chinaShipping" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "internationalShipping" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "tax" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "additionalCost" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "totalCost" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "marginType" "MarginType" NOT NULL DEFAULT 'PERCENTAGE',
  ADD COLUMN "marginPercentage" DECIMAL(8,2),
  ADD COLUMN "marginFixed" DECIMAL(18,0),
  ADD COLUMN "profit" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "calculatedSellingPrice" DECIMAL(18,0) NOT NULL DEFAULT 0,
  ADD COLUMN "roundingType" "PriceRoundingType" NOT NULL DEFAULT 'NONE',
  ADD COLUMN "stock" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "ExchangeRate"
  ALTER COLUMN "marketRate" TYPE DECIMAL(18,4) USING "marketRate"::DECIMAL(18,4),
  ALTER COLUMN "appliedRate" TYPE DECIMAL(18,4) USING "appliedRate"::DECIMAL(18,4),
  ALTER COLUMN "manualRate" TYPE DECIMAL(18,4) USING "manualRate"::DECIMAL(18,4),
  ADD COLUMN "buyRate" DECIMAL(18,4),
  ADD COLUMN "sourceDate" TIMESTAMP(3);
