import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdminPage } from "@/lib/require-admin";

const labels: Record<string, string> = { PENDING_REVIEW: "Baru", REVIEWED: "Sedang Dicek", QUOTATION_SENT: "Quotation Dikirim", CANCELLED: "Ditolak" };
export default async function AdminRequestsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  await requireAdminPage(); const params = await searchParams; const q = params.q || ""; const status = params.status || "";
  const requests = await prisma.jastipRequest.findMany({ where: { AND: [status ? { status: status as "PENDING_REVIEW" | "REVIEWED" | "QUOTATION_SENT" | "CANCELLED" } : {}, q ? { OR: [{ requestNumber: { contains: q, mode: "insensitive" } }, { productName: { contains: q, mode: "insensitive" } }, { productUrl: { contains: q, mode: "insensitive" } }, { user: { name: { contains: q, mode: "insensitive" } } }, { user: { phone: { contains: q } } }] } : {}] }, include: { user: true }, orderBy: { createdAt: "desc" } });
  return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold">Request Barang</h1><p className="mt-2 text-slate-500">Request nyata dari pelanggan.</p><form className="mt-7 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><input name="q" defaultValue={q} placeholder="Cari kode, customer, WhatsApp, barang..." className="field min-w-64 flex-1" /><select name="status" defaultValue={status} className="field w-52"><option value="">Semua status</option><option value="PENDING_REVIEW">Baru</option><option value="REVIEWED">Sedang Dicek</option><option value="QUOTATION_SENT">Quotation Dikirim</option><option value="CANCELLED">Ditolak</option></select><button className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Terapkan</button><Link href="/admin/requests" className="rounded-xl border px-4 py-2 text-sm">Reset Filter</Link></form><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Request</th><th className="p-4">Customer</th><th className="p-4">Barang</th><th className="p-4">Status</th><th className="p-4">Tanggal</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody>{requests.length ? requests.map((item) => <tr key={item.id} className="border-t"><td className="p-4 font-semibold">{item.requestNumber}</td><td className="p-4">{item.user?.name || "-"}<span className="block text-xs text-slate-500">{item.user?.phone || "-"}</span></td><td className="p-4">{item.productName}</td><td className="p-4">{labels[item.status]}</td><td className="p-4">{item.createdAt.toLocaleDateString("id-ID")}</td><td className="p-4 text-right"><Link href={`/admin/requests/${item.id}`} className="font-semibold text-indigo-600">Lihat Detail</Link></td></tr>) : <tr><td colSpan={6} className="p-12 text-center text-slate-500">Belum ada request barang.</td></tr>}</tbody></table></div></div>;
}
